FROM alpine

WORKDIR /opt/target
VOLUME /mounts/input /mounts/output

RUN apk --no-cache add \
    bash
COPY convert-ios.svg.sh .

CMD ["bash", "convert-ios.svg.sh", "/mounts/input", "/mounts/output"]
